### PR TITLE
[FEATURE] Add custom dnd migration support

### PR DESCRIPTION
**Pull request by darrensiegel**
This PR adds support for migrating Custom Drag and Drop questions.  

The main work here is:
1. The detection of this type of question, by looking for the custom javascript tag.
2. Conversion of the underlying mult_input question using the existing multi_input conversion code
3. Reading and conversion of the external layout file, moving the targetArea, initiators and layoutStyles into the activity content.
4. Detection of "non direct" image references within the layout styles, and addition of them into the media library, and replacement of their references with the full URL that the fill will exist as in Torus. 

To test this out, end to end:
1. Run Torus with the corresponding `custom-dnd` branch.
2. Generate a course digest of the test course that is embedded in this repo.
3. Ingest that digest into Torus.
4. Verify that you can preview, deliver and edit the two custom DnD questions that appear in a page in that course.

### CODE REVIEW

**Review by rgachuhi — CHANGES_REQUESTED** [review]
Getting errors when running the digest with the current default migration sample course.

Converting:  ./test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-inline-assessment/customdnd_inline.xml
oli_custom_dnd
oli_custom_dnd
Error: ENOENT: no such file or directory, open '/Users/cmuraff/staff/all_sources/torus/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-inline-assessment/test/course_packages/migration-4sdfykby_v_1_0-echo/content/webcontent/decay_series_background.png'
    at Object.openSync (node:fs:599:3)
    at Function.md5FileSync [as sync] (/Users/cmuraff/staff/all_sources/torus/course-digest/node_modules/md5-file/index.js:7:17)
    at flatten (/Users/cmuraff/staff/all_sources/torus/course-digest/src/media.ts:99:23)
    at /Users/cmuraff/staff/all_sources/torus/course-digest/src/media.ts:81:17
    at Array.forEach (<anonymous>)
    at Object.transformToFlatDirectoryURLReferences (/Users/cmuraff/staff/all_sources/torus/course-digest/src/media.ts:77:19)
    at /Users/cmuraff/staff/all_sources/torus/course-digest/src/convert.ts:285:13
    at Array.map (<anonymous>)
    at Object.updateNonDirectImageReferences (/Users/cmuraff/staff/all_sources/torus/course-digest/src/convert.ts:278:20)
    at /Users/cmuraff/staff/all_sources/torus/course-digest/src/index.ts:189:27
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/cmuraff/staff/all_sources/torus/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-inline-assessment/test/course_packages/migration-4sdfykby_v_1_0-echo/content/webcontent/decay_series_background.png'
}

**Comment by darrensiegel** [comment]
Interesting....  this works for me, and I think the dfiference might be that I'm specifying absolute paths from the command line:

```
 node ./node_modules/ts-node/dist/bin.js src/index.ts --operation convert --inputDir /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo  --outputDir ./out --specificOrg /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml  --specificOrgId migration-4sdfykby-1.0_default  --mediaUrlPrefix https://torus-media-dev.s3.amazonaws.com/media
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/welcome.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-assessment2/newe6ddd6fec8f54749a037ef13abd8df93.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/extra.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/mathml.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/entities.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/materials.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/composite.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-assessment2/assessment_with_selection.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/customdnd.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-learning_objectives/dd83841bc84045138faf6f3b7868c6dc.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-skills_model/c04c22b2337f412c8feff2c06e43cef3.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-skills_model/c04c22b2337f412c8feff2c06e43cef3.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-inline-assessment/newca1a54a0f56a4d429f5aff2c515cab08.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-assessment2/newc72f87db5a5543b5ae8582d2d4cd34a7.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-inline-assessment/weak_titration_lbd.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-assessment2-pool/complex_ion_pool.xml
Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-inline-assessment/customdnd_inline.xml
Do you want to create a zip archive? [Y/n] 
Done!
Do you want to upload media assets? [y/N] 
Skipping media upload.
```

**Comment by rgachuhi** [comment]
> Interesting.... this works for me, and I think the dfiference might be that I'm specifying absolute paths from the command line:
> 
> Can you try again and specify absolute paths like as follows:
> 
> ```
>  node ./node_modules/ts-node/dist/bin.js src/index.ts --operation convert --inputDir /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo  --outputDir ./out --specificOrg /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml  --specificOrgId migration-4sdfykby-1.0_default  --mediaUrlPrefix https://torus-media-dev.s3.amazonaws.com/media
> 
> 
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/organizations/default/organization.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/welcome.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-assessment2/newe6ddd6fec8f54749a037ef13abd8df93.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/extra.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/mathml.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/entities.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/materials.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/composite.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-assessment2/assessment_with_selection.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-workbook_page/customdnd.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-learning_objectives/dd83841bc84045138faf6f3b7868c6dc.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-skills_model/c04c22b2337f412c8feff2c06e43cef3.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-skills_model/c04c22b2337f412c8feff2c06e43cef3.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-inline-assessment/newca1a54a0f56a4d429f5aff2c515cab08.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-assessment2/newc72f87db5a5543b5ae8582d2d4cd34a7.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-inline-assessment/weak_titration_lbd.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-assessment2-pool/complex_ion_pool.xml
> Converting:  /Users/darrensiegel/dev/course-digest/test/course_packages/migration-4sdfykby_v_1_0-echo/content/x-oli-inline-assessment/customdnd_inline.xml
> Do you want to create a zip archive? [Y/n] 
> Done!
> Do you want to upload media assets? [y/N] 
> Skipping media upload.
> ```

Yep, works when I use fully qualified file paths

**Comment by eliknebel** [comment]
I ran into the same issue as Raphael, where the webcontent image could not be found when using a relative path. Using an absolute path fixes it

**Pull request merged**
